# Generated by Django 4.2 on 2023-07-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacanct',
            new_name='Vacancy',
        ),
    ]
