# Generated by Django 4.2 on 2023-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0002_rename_vacanct_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюмы',
            },
        ),
    ]
