# Generated by Django 4.2 on 2023-07-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_itemgroup_item_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.itemgroup'),
        ),
    ]
