# Generated by Django 4.2 on 2023-07-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_alter_item_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
    ]
