# Generated by Django 4.2 on 2023-07-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_remove_item_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemGroup',
        ),
    ]
