# Generated by Django 2.2 on 2023-07-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUsers',
        ),
    ]
