# Generated by Django 4.2 on 2023-07-06 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestUsers',
            new_name='Profile',
        ),
    ]
