# Generated by Django 4.2 on 2023-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_homeworkmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='creadit_card',
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='credit_card',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='city',
            field=models.CharField(blank=True, default='0', max_length=36),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=0),
        ),
    ]
