# Generated by Django 4.2 on 2023-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
