# Generated by Django 4.2 on 2023-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_home_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement_home_work',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='advertisement_home_work',
            name='veiws_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
