# Generated by Django 4.2 on 2023-06-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_home_work_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement_home_work',
            new_name='Advertisement',
        ),
    ]
