# Generated by Django 4.2 on 2023-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_advertisement_home_work_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_testing_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
