# Generated by Django 4.2 on 2023-06-14 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_my_testing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_testing_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_testing_model',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='my_testing_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='my_testing_model',
            name='veiws_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
