# Generated by Django 4.2 on 2023-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='conn',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='name',
        ),
        migrations.AddField(
            model_name='regions',
            name='name',
            field=models.ManyToManyField(to='advertisement.advertisement'),
        ),
    ]
