# Generated by Django 4.2 on 2023-06-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_remove_regions_conn_remove_regions_name_regions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_type',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('conn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advertisement.advertisement')),
            ],
        ),
    ]
