# Generated by Django 4.2 on 2023-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_advertisement_type2_delete_advertisement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement_type2',
            name='conn',
        ),
        migrations.AddField(
            model_name='advertisement_type2',
            name='conn',
            field=models.ManyToManyField(to='advertisement.advertisement'),
        ),
    ]
