# Generated by Django 4.2 on 2023-06-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_advertisement_type1_delete_advertisement_type2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
