# Generated by Django 4.2 on 2023-06-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
