# Generated by Django 4.2 on 2023-06-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя продавца'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisement.advertisementstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Заголовок'),
        ),
    ]
