# Generated by Django 4.2 on 2023-06-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_author_rubrik_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisement.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rubrik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrik', to='advertisement.rubrik', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='advertisement_type1',
            name='conn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisement.advertisement'),
        ),
    ]
