# Generated by Django 4.2 on 2023-06-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0019_alter_advertisement_author_alter_advertisement_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement_type1',
            name='conn',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='advertisement.advertisement_type1', verbose_name='Тип'),
        ),
    ]
