# Generated by Django 2.2 on 2023-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('decription', models.TextField(blank=True, verbose_name='описание')),
                ('weight', models.FloatField(verbose_name='вес')),
            ],
        ),
    ]
