# Generated by Django 4.2 on 2023-06-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='status',
            field=models.CharField(choices=[['a', 'Active'], ['i', 'Incactive']], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='news.newsmodel'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='text',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=models.TextField(verbose_name='Содержимое новости'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date_created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date_redacted',
            field=models.DateField(verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='flag_active',
            field=models.BooleanField(verbose_name='Фейк?'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
