# Generated by Django 4.2 on 2023-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_goodshw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodshw',
            name='file',
            field=models.FileField(blank=True, upload_to='files/homework'),
        ),
    ]
