# Generated by Django 4.2 on 2023-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_alter_goodshw_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodshw',
            name='file',
            field=models.FileField(upload_to='files/homework'),
        ),
    ]
