# Generated by Django 2.2 on 2023-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=70)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
