# Generated by Django 4.2 on 2023-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='authors',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='authors',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='personal_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='authors',
            name='second_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='authors',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='univercity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='authors',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
