# Generated by Django 4.2 on 2023-06-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_authors_birth_date_authors_city_authors_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='univercity',
            new_name='university',
        ),
    ]
