# Generated by Django 4.2 on 2023-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0005_rename_univercity_authors_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[['d', 'Draft'], ['r', 'Review'], ['p', 'Published']], default='d', max_length=1),
        ),
    ]
